ARG NODE_VERSION=20.19.0

FROM node:${NODE_VERSION}-slim AS base

ARG PORT=3000

WORKDIR /src

# Build
FROM base AS build

COPY package.json package-lock.json .env ./
RUN npm ci --omit=dev --ignore-scripts

COPY . .
RUN npm run build

# Run
FROM base

ENV PORT=$PORT
ENV NODE_ENV=production

COPY --from=build /src/.output /src/.output

# Remove unnecessary files to reduce image size
RUN rm -rf /root/.npm /tmp/*

# Expose port
EXPOSE 9006

CMD [ "node", ".output/server/index.mjs" ]
